
[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 14.0

[font.bold]
family = "SauceCodePro NFM"
style = "Medium"

[font.italic]
family = "SauceCodePro NFM"
style = "Italic"

[font.normal]
family = "SauceCodePro NFM"
style = "Regular"

[terminal.shell]
args = ["--login"]
program = "/usr/bin/fish"

[window]
# decorations = "none"
opacity = 0.9
dimensions = { columns = 90, lines = 30 }

[general]
import = ["/home/sy/.config/alacritty/catppuccin-macchiato.toml"]

[terminal]
